#!/bin/sh

# $FreeBSD: 13.1 2022 sensen
#
# PROVIDE: plone
# REQUIRE: NETWORKING LOGIN DAEMON
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable plone:
#
# plone_enable="YES"
#

. /etc/rc.subr

name="plone" # How the service will be invoked from service
rcvar="${name}_enable"  # The variable in rc.conf that will allow this service to run


load_rc_config $name # Loads the config file, if relevant.
# pidfile=/var/run/${name}.pid

start_cmd="cd /usr/home/sensen/plone6/plonebuildout; bin/instance start"

run_rc_command "$1"